app/models/models.py
from engine.db import db
from flask_login import UserMixin


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

    def __repr__(self) -> str:
        return super().__repr__()
    
class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    author = db.Column(db.String(80), nullable=False)
    year = db.Column(db.Integer, nullable=False)
    description = db.Column(db.String(500), nullable=False)

    def __repr__(self):
        return '<Book %r>' % self.title

app/routes/routes.py
from datetime import date
import json
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from models.models import User, Book
from engine.db import db 

app_route = Blueprint('route', __name__)

@app_route.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('route.profile'))
    else:
        return render_template('index.html')

@app_route.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('route.books'))
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('route.books'))
        else:
            flash('Invalid username or password')
    return render_template('login.html')

@app_route.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('route.profile'))
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username already taken')
        else:
            hashed_password = generate_password_hash(password)
            new_user = User(username=username, password=hashed_password, email=email)
            db.session.add(new_user)
            db.session.commit()
            flash('Account created successfully')
            return redirect(url_for('route.login'))
    return render_template('register.html')

@app_route.route('/profile')
def profile():
    if current_user.is_authenticated:
        return render_template('profile.html', user=current_user)
    else:
        return redirect(url_for('route.login'))

@app_route.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('route.index'))

@app_route.route('/books', methods=['GET', 'POST'])
def books():
    if not current_user.is_authenticated:
        return redirect(url_for('route.login'))
    else:
        books = Book.query.all()
        if request.method == 'POST':
            match request.form['oper']:
                case "import":
                    return redirect(url_for('route.import_json'))
                case "export":
                    books_list = []
                    for book in books:
                        books_list.append({"название": book.title,
                                        "автор": book.author,
                                        "год": book.year,
                                        "описание": book.description})
                    with open(f'app/export/export_{date.today()}.json', 'w', encoding="utf-8") as file:
                        json.dump(books_list, file, ensure_ascii=False)
                        
                    flash('Экспорт файл завершен')
        return render_template('books.html', books=books)

@app_route.route('/import_json', methods=['GET', 'POST'])
def import_json():
    if not current_user.is_authenticated:
        return redirect(url_for('route.login'))
    else:
        if request.method == 'POST' and request.form['file'] != '':
            with open (request.form['file']) as file:
                books = json.load(file)
            for book in books:
                new_book = Book(title=book['название'],
                                author=book['автор'],
                                year=book['год публикации'],
                                description=book['описание'])
                db.session.add(new_book)
            db.session.commit()
            return redirect(url_for('route.books'))
    return render_template('import.html')

    
@app_route.route('/book/<int:book_id>')
def book_detail(book_id):
    book = Book.query.get_or_404(book_id)
    return render_template('book.html', book=book)

@app_route.route('/del_book/<int:book_id>', methods=['GET', 'POST'])
def book_delete(book_id):
    if not current_user.is_authenticated:
        return redirect(url_for('route.login'))
    else:
        del_book = Book.query.get_or_404(book_id)
        if request.method == 'POST':
            # del_book = Book.query.get_or_404(book_id)
            db.session.delete(del_book)
            db.session.commit()
            return redirect(url_for('route.books'))
    return render_template('del_book.html', book=del_book)

@app_route.route('/add_book', methods=['GET', 'POST'])
def add_book():
    if not current_user.is_authenticated:
        return redirect(url_for('route.login'))
    else:
        if request.method == 'POST':
            book_name = request.form['book_name']
            author = request.form['author']
            year = request.form['year']
            description = request.form['description']
            new_book = Book(title=book_name, author=author, year=year, description=description)
            db.session.add(new_book)
            db.session.commit()
            flash('Добавлена новая книга')
            return redirect(url_for('route.books'))
    return render_template('add_book.html')

@app_route.route('/update_book/<int:book_id>', methods=['GET', 'POST'])
def update_book(book_id):
    
    if not current_user.is_authenticated:
        return redirect(url_for('route.login'))
    else:
        update_book = Book.query.get_or_404(book_id)
        if request.method == 'POST':
            book_name = request.form['book_name']
            author = request.form['author']
            year = request.form['year']
            description = request.form['description']
            db.session.query(Book).filter(Book.id == book_id).update({"title": book_name,
                                                                    "author": author,
                                                                    "year": year,
                                                                    "description": description})
            db.session.commit()
            return redirect(url_for('route.books'))
    return render_template('update_book.html', book=update_book)

app/templates/add_book.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Добавление книги</h1>
                </div>
                <div class="card-body">
                    <form method="post">
                        <div class="mb-3">
                            <label for="book_name" class="form-label">Название книги:</label>
                            <input type="text" class="form-control" id="book_name" name="book_name" required>
                        </div>
                        <div class="mb-3">
                            <label for="author" class="form-label">Автор:</label>
                            <input type="text" class="form-control" id="author" name="author" required>
                        </div>
                        <div class="mb-3">
                            <label for="year" class="form-label">Год издания:</label>
                            <input type="text" class="form-control" id="year" name="year" required>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Описание:</label>
                            <textarea class="form-control" id="description" name="description" required></textarea>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Добавить книгу</button>
                            <a class="btn btn-danger" href="/books">Отменить</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/books">Библиотека</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end"
            id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/profile">Аккаунт</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('route.logout') }}">Выйти</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container my-3">
    {% block content %}
    {% endblock %}
    
</div>

</body>
</html>

app/templates/book.html
{% extends 'base.html' %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ book.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
        <p class="card-text">{{book.year}}</p>
        <p class="card-text">{{ book.description }}</p>
        <a href="{{ url_for('route.books') }}" class="btn btn-secondary">&larr; Назад</a>
    </div>
</div>
{% endblock %}

app/templates/books.html
{% extends 'base.html' %}

{% block title %}Библиотека{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-danger">
                <ul>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST">
            <div class="col">
                <a class="btn btn-primary" href="{{url_for('route.add_book')}}" >Добавить книгу</a>
                <button class="btn btn-primary" type="submit" id="import" name="oper" value="import">Импорт книг</button>
                <button class="btn btn-primary" id="export" type="submit"name="oper" value="export">Экспорт книг</button>
            </div>    
        </form>
            

            <div class="row">
                {% for book in books %}
                <div class="col-sm-6 col-md-6">
                    <div class="card">
                        <div style="position: relative;">
                        <div class="card-body" style="min-height: 150px;">
                            <h5 class="card-title">{{ book.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
                            <div class="card-text">{{ book.description[:50] }}...</div>
                            <a href="{{ url_for('route.book_detail', book_id=book.id) }}" class="btn btn-primary"
                                style="position: absolute; bottom: 15px; right: 15px;">Подробнее</a>
                            <a href="{{ url_for('route.book_delete', book_id=book.id) }}" class="btn btn-danger"
                                style="position: absolute; bottom: 15px; right: 140px;">Удалить</a>
                            <a href="{{ url_for('route.update_book', book_id=book.id) }}" class="btn btn-success"
                                style="position: absolute; bottom: 15px; right: 240px;">Редактировать</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/del_book.html
{% extends 'base.html' %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
<form method="post">
    <div class="card">
        <h6 class="text-center">ПОДТВЕРДИТЕ УДАЛЕНИЕ КНИГИ</h6>
        <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
            <p class="card-text">{{ book.description }}</p>
            <div class="text-center">
                <button type="submit" class="btn btn-danger" style="position: relative;">Удалить</button>
                <a class="btn btn-success" href="{{ url_for('route.books') }}">&larr; Назад</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

app/templates/import.html
{% extends 'base.html' %}

{% block title %}Библиотека{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-danger">
                <ul>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST">
            <div>
                <input type="file" id="file" name="file" multiple />
                <button btn="btn btn-primary" type="submit">Импорт выбранного файла</button>
            </div>
        </form>
        
        
            

    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% if current_user.is_authenticated %}
    <p class="mt-5">Привет, {{ current_user.username }}!</p>
    <a href="{{ url_for('route.profile') }}" class="btn btn-primary mt-3">Мой профиль</a>
    <a href="{{ url_for('route.logout') }}" class="btn btn-secondary mt-3">Выход</a>
    {% else %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Добро пожаловать в Библиотеку</h1>
                </div>
                <div class="card-body">
                    <p>Пожалуйста, <a href="{{ url_for('route.login') }}">войдите</a> или <a
                            href="{{ url_for('route.register') }}">зарегистрируйтесь</a> для просмотра своего профиля.</p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Вход на сайт</h1>
                </div>
                <div class="card-body">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    {% endwith %}
                    <form method="post">
                        <div class="mb-3">
                            <label for="username" class="form-label">Логин:</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Пароль:</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Войти</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Привет, {{ user.username }}</h1>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-center mb-4">
                        <img src="{{ url_for('static', filename='images/default.jpg') }}"
                            class="rounded-circle profile-photo" alt="Profile photo">
                    </div>
                    <p>Ваши данные:</p>
                    <p>Имя: {{user.username}}</p>
                    <p>Email: {{ user.email }}</p>
                    <div class="text-center">
                        <a href="{{ url_for('route.logout') }}" class="btn btn-secondary">Выход</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Регистрация</h1>
                </div>
                <div class="card-body">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    {% endwith %}
                    <form method="post">
                        <div class="mb-3">
                            <label for="username" class="form-label">Логин:</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Пароль:</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email:</label>
                            <input type="email" class="form-control" id="email" name="email" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/update_book.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Редактирование книги</h1>
                </div>
                <div class="card-body">
                    <form method="post">
                        <div class="mb-3">
                            <label for="book_name" class="form-label">Название книги:</label>
                            <input type="text" class="form-control" id="book_name" name="book_name" value="{{book.title}}">
                        </div>
                        <div class="mb-3">
                            <label for="author" class="form-label">Автор:</label>
                            <input type="text" class="form-control" id="author" name="author" value="{{book.author}}" required>
                        </div>
                        <div class="mb-3">
                            <label for="year" class="form-label">Год издания:</label>
                            <input type="text" class="form-control" id="year" name="year" value="{{book.year}}" required>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Описание:</label>
                            <textarea class="form-control" id="description" name="description" required>{{book.description}}</textarea>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                            <a class="btn btn-danger" href="/books">Отменить</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}